---
exclude: .git|.dvc|.bzr|.direnv|.eggs|.mypy_cache|.tox|.venv|__packages__|_build|build|dist|venv
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/hakancelikdev/unimport
    rev: 1.2.1
    hooks:
      - id: unimport
        args: [--disable-auto-discovery-config, --config=pyproject.toml]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: 0.3.4
    hooks:
      - id: auto-walrus
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0]
  # - repo: https://github.com/fastai/nbdev
  #   rev: 2.2.10
  #   hooks:
  #     - id: nbdev_clean
  #     - id: nbdev_export
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-black
        language_version: python3.11
        additional_dependencies: [black==23.3.0]
      - id: nbqa-ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: nbqa-mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0, mypy==v1.2.0]
      - id: nbqa-pyupgrade
      - id: nbqa-check-ast
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        args: [--lock]
      - id: poetry-export
        args:
          - -f
          - requirements.txt
          - -o
          - requirements.txt
          - --without-hashes
      - id: poetry-install
        args: [--sync]
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.16.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: [--exclude-file=poetry.lock]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-added-large-files
      - id: debug-statements
