---
EPOCHS: 10
BATCH_SIZE: 64
LEARNING_RATE: 0.001
N_WORKERS: 2
BEST_VAL: 1e9
BEST_MODEL_PATH: /checkpoints/best_model.pth
CHECKPOINT_PATH: /checkpoints/
HEIGHT: 256
WIDTH: 256
CHANNELS: 3
N_IMAGES: 1000
DTYPE: np.uint8
