---
wandb_version: 1
EPOCHS:
  desc:
  value: 10
BATCH_SIZE:
  desc:
  value: 64
LEARNING_RATE:
  desc:
  value: 0.001
N_WORKERS:
  desc:
  value: 2
BEST_VAL:
  desc:
  value: 1000000000.0
BEST_MODEL_PATH:
  desc:
  value: /checkpoints/best_model.pth
CHECKPOINT_PATH:
  desc:
  value: /checkpoints/
_wandb:
  desc:
  value:
    python_version: 3.10.12
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719275714
    t:
      1: [1, 41, 55]
      2: [1, 41, 55]
      3: [16, 23]
      4: 3.10.12
      5: 0.17.3
      8: [5]
      13: linux-x86_64
